"""
Review page — inspect and approve rename suggestions.

Displays the proposals generated by SuggestionEngine in an editable table.
The user can accept, reject, or manually edit each suggestion before
proceeding to the apply step.
"""
